packages:
    - packages/*
    - servers/*
    - starters/*
    - samples/*
    - tests/*
ignoredBuiltDependencies:
    - protobufjs
onlyBuiltDependencies:
    - "@firebase/util"
    - "@scarf/scarf"
    - "@swc/core"
    - better-sqlite3
