app:
    name: "nodeboot-koa"
    platform: "node-boot-benchmark"
    environment: "production"
    port: 4014

api:
    routePrefix: ""
    nullResultCode: 200
    undefinedResultCode: 204

logger:
    level: "warn"

persistence:
    type: "postgres"
    postgres:
        host: "localhost"
        port: 5433
        username: "postgres"
        password: "postgres"
        database: "nodeboot_koa"
        synchronize: true
