node-boot:
    # App configurations
    app:
        name: "facts-service"
        platform: "tech-insights"
        environment: "development"
        defaultErrorHandler: false
        port: 10000

    api:
        routePrefix: "/api"
        nullResultCode: 200
        undefinedResultCode: 200
        paramOptions:
            required: false
        validations:
            enable: true
            enableDebugMessages: false
            skipUndefinedProperties: false
            skipNullProperties: false
            skipMissingProperties: false
            whitelist: false
            forbidNonWhitelisted: false
            forbidUnknownValues: false
            stopAtFirstError: false

    # Server configurations
    server:
        cors:
            origin: "*"
            methods:
                - GET
                - POST
                - DELETE
                - PUT
            credentials: true
            maxAge: 55000
            cacheControl: 4096
            preflightContinue: true
            optionsSuccessStatus: 204
            preflight: true
            strictPreflight: false
            exposedHeaders: []
            allowedHeaders: []
        multipart:
            throwFileSizeLimit: true
            limits:
                fieldNameSize: 128
                fieldSize: 128
                fields: 10
                fileSize: 4096
                files: 5
                headerPairs: 10

    # Storage configurations
    persistence:
        type: "better-sqlite3"
        synchronize: true # FIXME create tables automatically through migrations instead of synchronize,
        cache: true
        better-sqlite3:
            database: "fastify-sample.db"
