integrations:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
        sns:
            region: ${AWS_SNS_REGION}

reflectoring:
    aws:
        sns:
            topic-arn: ${AWS_SNS_TOPIC_ARN}
